### ISSUE TITLE
Add generic parser framework

### ISSUE THREAD

**Issue by Tishj** [42-Ikole-Systems/TMK-SH#4]

**Comment by mraasvel** [comment]
```C++
optional<Ast::Node> Parser::List() {
    Parser(this, {
        Sequence({
            AndOr(), SeparatorOp(), List()
        }, [&](vector<Ast::Node> &result) -> Ast::Node {
            assert(result.size() == 3);
            // define logic to assemble node ...
        }),
        Sequence({
            AndOr,
        })
    });
}
```
Implement it in a generic way for example like above.

- [ ] Take a sequence of ORed grammar rules, which recursively parses them, taking the first one that matches
- [ ] Take a method that constructs the correct AST node based on which sequence matched

For example:
```
list : and_or separator_op list
      | and_or
```
Could be defined in the code like:
```C++
Sequence(
   { AndOr, SeparatorOp, List },
   { AndOr }
)
```

**Comment by Tishj** [comment]
We now have a GrammarRule and GrammarRule::Option to implement the logic of assembling the nodes based on the sequences of grammar rules that the grammar rule has defined it accepts valid.

Now we just need to add the generic logic that accepts the sequences of rules and figures out which sequence (if any) fits the provided tokens, and call the right GrammarRule::Option's node assembler
